import { Hono } from 'hono';

/**
 * The Tabula backend. All routes live under /api (the basePath).
 * This single `app` is mounted into the Astro worker via
 * src/pages/api/[...path].ts — no separate deploy.
 *
 * `Bindings` is the global ambient `Env` generated by `wrangler types`
 * (run `pnpm generate-types` after editing bindings in wrangler.jsonc).
 * Add R2 / D1 / AI bindings there and they become available as `c.env.*`.
 */
export const app = new Hono<{ Bindings: Env }>().basePath('/api');

app.get('/ping', (c) => c.json({ ok: true, service: 'tabula-api' }));

// Mount feature routers here as you build them, e.g.
// app.route('/upload', uploadRoutes);
// app.route('/health', healthRoutes);
// app.route('/chat', chatRoutes);

export type AppType = typeof app;
